import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useRef, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { ChapterMenu } from "./components/ChapterMenu";
import { CourseProgress } from "./components/CourseProgress";
import { ModeControls, type PlaybackMode } from "./components/ModeControls";
import { ProgressBar } from "./components/ProgressBar";
import { QuizPanel } from "./components/QuizPanel";
import { Stage } from "./components/Stage";
import { SubtitleStep } from "./components/SubtitleStep";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useCourseLoader, readCourseIdFromUrl } from "./hooks/useCourseLoader";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

/**
 * Course mode entry point.
 *
 * Default mode is "course" (reads `?course=<id>` from the URL and fetches
 * the matching course.json). To force single-video mode, set the page
 * address with no `?course=` and pass `mode: "single"` below, or just
 * rename the call site.
 */
export default function App() {
  const [mode] = useState<PlaybackMode>(() => {
    if (typeof window === "undefined") return "manual";
    return (window.localStorage.getItem("cf-mode") as PlaybackMode | null) || "manual";
  });
  const [playbackMode, setPlaybackMode] = useState<PlaybackMode>(mode);

  // Course mode is the default — read the chapter list from course.json.
  // To force single-video mode, pass `mode: "single"` here and the
  // local `CHAPTERS` array will be used instead.
  const loader = useCourseLoader({
    mode: "course",
    singleVideoChapters: CHAPTERS,
  });

  // While course.json is loading, show a small loader. The case of
  // missing/error course.json is handled inside <CourseView> below.
  if (loader.status === "loading") {
    return (
      <div className="app-root app-root--loading">
        <div className="app-loading serif-cn">载入中…</div>
      </div>
    );
  }

  if (loader.status === "missing" || loader.status === "error") {
    return (
      <div className="app-root app-root--loading">
        <div className="app-error">
          <div className="app-error-title serif-cn">course.json 缺失或无效</div>
          <div className="app-error-body serif-cn">{loader.message}</div>
          <div className="app-error-hint label-mono">
            请先在 public/ 目录生成 course.json (参考 references/COURSE-MODE.md § 模式判断 checklist)
          </div>
        </div>
      </div>
    );
  }

  return (
    <CourseView
      course={loader.course}
      chapters={loader.chapters}
      playbackMode={playbackMode}
      onModeChange={setPlaybackMode}
    />
  );
}

/* ========================================================================
 * CourseView — the real view, mounted only when course.json is loaded.
 * ========================================================================
 */

interface CourseViewProps {
  course: import("./registry/types").CourseJson;
  chapters: import("./registry/types").ChapterDef[];
  playbackMode: PlaybackMode;
  onModeChange: (m: PlaybackMode) => void;
}

function CourseView({ course, chapters, playbackMode, onModeChange }: CourseViewProps) {
  // Key the stepper by the loaded courseId so two courses served from
  // the same origin keep independent progress (per the SKILL note on
  // storageKey naming).
  const courseId = `${course.courseId}-${readCourseIdFromUrl()}`;
  const stepper = useStepper(chapters, courseId);
  const { mode, autoStarted, setAutoStarted } = useAutoMode();

  const ch = chapters[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Play/pause toggle — independent of playback mode. When paused:
  //   * audio element is paused
  //   * auto-advance is held (we override onAutoAdvance to a no-op)
  //   * manual click on Stage still works (lets the user navigate
  //     "behind the pause curtain") — but to keep behaviour simple,
  //     we also block manual advance while paused.
  const [isPaused, setIsPaused] = useState(false);

  // Persist mode choice
  useEffect(() => {
    try {
      window.localStorage.setItem("cf-mode", playbackMode);
    } catch {
      /* ignore */
    }
  }, [playbackMode]);

  // Reset pause state when the cursor changes (new step = fresh play)
  useEffect(() => {
    setIsPaused(false);
  }, [stepper.cursor.chapter, stepper.cursor.step]);

  const handleAdvance = useCallback(() => {
    if (isPaused) return;
    stepper.next();
  }, [stepper, isPaused]);

  useAudioPlayer({
    src: `/audio/${ch.id}/${stepper.cursor.step + 1}.mp3`,
    paused: isPaused,
    mode,
    autoStarted,
    onAutoAdvance: handleAdvance,
    estimateFallbackMs: estimateMs(stepText),
  });

  const onAdvance = useCallback(() => {
    if (mode === "auto" && !autoStarted) return;
    if (isPaused) return;
    stepper.next();
  }, [mode, autoStarted, stepper, isPaused]);

  // Demo: a quiz panel is hard-coded at the last step of the last
  // chapter. Real projects should expose `quiz` data via the
  // course.json or per-chapter metadata.
  const isLastStep =
    stepper.cursor.chapter === chapters.length - 1 &&
    stepper.cursor.step === ch.narrations.length - 1;

  // Fullscreen toggle (Fullscreen API on the main area)
  const fsRef = useRef<HTMLDivElement | null>(null);
  const [isFs, setIsFs] = useState(false);

  // ChapterMenu visibility — collapsed by default to give Stage the full
  // 1920×1080 viewport. Reopens on hover near the left edge or on the
  // explicit "≡" button in the top-left corner. Closes when the cursor
  // leaves both the menu and the trigger strip.
  const [menuOpen, setMenuOpen] = useState(false);
  const menuHideTimer = useRef<number | null>(null);
  function showMenu() {
    if (menuHideTimer.current != null) {
      window.clearTimeout(menuHideTimer.current);
      menuHideTimer.current = null;
    }
    setMenuOpen(true);
  }
  function hideMenuDelayed() {
    if (menuHideTimer.current != null) window.clearTimeout(menuHideTimer.current);
    menuHideTimer.current = window.setTimeout(() => setMenuOpen(false), 220);
  }
  const toggleFullscreen = useCallback(() => {
    if (!fsRef.current) return;
    if (!document.fullscreenElement) {
      fsRef.current.requestFullscreen().catch(() => {});
      setIsFs(true);
    } else {
      document.exitFullscreen().catch(() => {});
      setIsFs(false);
    }
  }, []);

  const togglePause = useCallback(() => setIsPaused((p) => !p), []);

  // Keyboard shortcuts:
  //   Space  → toggle play / pause
  //   F      → toggle fullscreen
  //   M      → cycle playback mode (manual → audio → auto)
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement | null;
      if (
        target instanceof HTMLInputElement ||
        target instanceof HTMLTextAreaElement
      ) return;
      if (e.key === " " || e.code === "Space") {
        e.preventDefault();
        e.stopPropagation();
        // Drop focus from any focused button so a subsequent Space
        // doesn't re-trigger that button's click (browser default
        // behavior). Without this, hitting Space while a button is
        // focused can both pause AND advance.
        if (document.activeElement instanceof HTMLElement) {
          document.activeElement.blur();
        }
        // Space semantics — never advance the stepper:
        //   1. AutoStartGate visible (page just opened with ?auto=1,
        //      user hasn't gestured yet) → dismiss the gate and start
        //      auto playback. (Bypass the pause flag entirely.)
        //   2. AutoStartGate dismissed + isPaused → resume.
        //   3. AutoStartGate dismissed + !isPaused → pause.
        if (mode === "auto" && !autoStarted) {
          setAutoStarted(true);
        } else {
          togglePause();
        }
      } else if (e.key === "f" || e.key === "F") {
        e.preventDefault();
        toggleFullscreen();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [togglePause, toggleFullscreen, mode, autoStarted, setAutoStarted]);

  return (
    <div className={`app-root ${menuOpen ? "app-root--menu-open" : ""}`} ref={fsRef}>
      <ChapterMenu
        course={course}
        currentChapterId={ch.id}
        jumpTo={(chapterIndex, step) => stepper.jumpToChapter(chapterIndex, step)}
        onMouseEnter={showMenu}
        onMouseLeave={hideMenuDelayed}
      />

      <div
        className="cm-trigger"
        onMouseEnter={showMenu}
        onMouseLeave={hideMenuDelayed}
        onFocus={showMenu}
      >
        <button
          type="button"
          className="cm-trigger-btn"
          onClick={() => (menuOpen ? setMenuOpen(false) : showMenu())}
          aria-label="显示课程菜单"
          aria-expanded={menuOpen}
          title="菜单"
          data-no-advance
        >
          <span aria-hidden="true">≡</span>
        </button>
      </div>

      <div className="app-main">
        <AutoStartGate
          visible={mode === "auto" && !autoStarted}
          onStart={() => setAutoStarted(true)}
        />

        <div className="app-stage-area">
          <Stage onAdvance={onAdvance} layout="embedded">
            <Cmp step={stepper.cursor.step} />
          </Stage>
        </div>

        <SubtitleStep chapters={chapters} cursor={stepper.cursor} />

        {course.courseId === "single" ? (
          <ProgressBar
            chapters={chapters}
            cursor={stepper.cursor}
            onJumpChapter={(idx, step) => stepper.jumpToChapter(idx, step)}
          />
        ) : (
          <CourseProgress chapters={chapters} cursor={stepper.cursor} />
        )}

        <ModeControls
          mode={playbackMode}
          onModeChange={onModeChange}
          onFullscreen={toggleFullscreen}
          isFullscreen={isFs}
          isPaused={isPaused}
          onTogglePause={togglePause}
          hint="Space 暂停/播放 · M 切模式 · F 全屏 · 鼠标点屏幕推进"
        />

        {isLastStep && (
          <div className="app-quiz-overlay">
            <QuizPanel
              question={{
                id: "l1-reaction",
                type: "single",
                prompt: "这一课你最有收获的是哪个术语?",
                options: [
                  { id: "a", label: "IDE 集成开发环境" },
                  { id: "b", label: "笛卡尔坐标" },
                  { id: "c", label: "顺序执行" },
                ],
                rationale: "三个都是核心概念, 选择你认为最常用于你未来工作的。",
              }}
              onSubmit={() => {
                /* TODO: surface a "submitted" badge / persistence */
              }}
            />
          </div>
        )}
      </div>
    </div>
  );
}
