import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useRef, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { ChapterMenu } from "./components/ChapterMenu";
import { CourseProgressReadout, computeSegmentProgress } from "./components/CourseProgress";
import { AppDock } from "./components/AppDock";
import { ModeControls, type PlaybackMode } from "./components/ModeControls";
import { ProgressBar } from "./components/ProgressBar";
import { QuizPanel } from "./components/QuizPanel";
import { Stage } from "./components/Stage";
import { SubtitleStep } from "./components/SubtitleStep";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useCourseLoader, readCourseIdFromUrl } from "./hooks/useCourseLoader";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

/**
 * Course mode entry point.
 *
 * Default mode is "course" (reads `?course=<id>` from the URL and fetches
 * the matching course.json). To force single-video mode, set the page
 * address with no `?course=` and pass `mode: "single"` below, or just
 * rename the call site.
 */
export default function App() {
  const [mode] = useState<PlaybackMode>(() => {
    if (typeof window === "undefined") return "manual";
    return (window.localStorage.getItem("cf-mode") as PlaybackMode | null) || "manual";
  });
  const [playbackMode, setPlaybackMode] = useState<PlaybackMode>(mode);

  // Course mode is the default — read the chapter list from course.json.
  // To force single-video mode, pass `mode: "single"` here and the
  // local `CHAPTERS` array will be used instead.
  const loader = useCourseLoader({
    mode: "course",
    singleVideoChapters: CHAPTERS,
  });

  // While course.json is loading, show a small loader. The case of
  // missing/error course.json is handled inside <CourseView> below.
  if (loader.status === "loading") {
    return (
      <div className="app-root app-root--loading">
        <div className="app-loading serif-cn">载入中…</div>
      </div>
    );
  }

  if (loader.status === "missing" || loader.status === "error") {
    return (
      <div className="app-root app-root--loading">
        <div className="app-error">
          <div className="app-error-title serif-cn">course.json 缺失或无效</div>
          <div className="app-error-body serif-cn">{loader.message}</div>
          <div className="app-error-hint label-mono">
            请先在项目根生成 course.json (参考 references/COURSE-STRUCTURE.md § 课程结构)
          </div>
        </div>
      </div>
    );
  }

  return (
    <CourseView
      course={loader.course}
      chapters={loader.chapters}
      playbackMode={playbackMode}
      onModeChange={setPlaybackMode}
    />
  );
}

/* ========================================================================
 * CourseView — the real view, mounted only when course.json is loaded.
 * ========================================================================
 */

interface CourseViewProps {
  course: import("./registry/types").CourseJson;
  chapters: import("./registry/types").ChapterDef[];
  playbackMode: PlaybackMode;
  onModeChange: (m: PlaybackMode) => void;
}

function CourseView({ course, chapters, playbackMode, onModeChange }: CourseViewProps) {
  // Key the stepper by the loaded courseId so two courses served from
  // the same origin keep independent progress (per the SKILL note on
  // storageKey naming).
  const courseId = `${course.courseId}-${readCourseIdFromUrl()}`;
  const stepper = useStepper(chapters, courseId);
  const { mode, autoStarted, setAutoStarted } = useAutoMode();

  const ch = chapters[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Data-driven interaction: each chapter may declare `quizzes`
  // (see ChapterDef.quizzes / QuizStep). The runtime overlays the
  // QuizPanel at the matching step and holds advancement until the
  // learner submits (see quizOpen below).
  const quiz = ch.quizzes?.find((q) => q.step === stepper.cursor.step);

  // Play/pause toggle — independent of playback mode. When paused:
  //   * audio element is paused
  //   * auto-advance is held (we override onAutoAdvance to a no-op)
  //   * manual click on Stage still works (lets the user navigate
  //     "behind the pause curtain") — but to keep behaviour simple,
  //     we also block manual advance while paused.
  const [isPaused, setIsPaused] = useState(false);
  // Tracks whether the active quiz (if any) has been submitted. While a
  // quiz is open and unanswered, advancement is held (manual + auto).
  const [quizAnswered, setQuizAnswered] = useState(false);

  // Persist mode choice
  useEffect(() => {
    try {
      window.localStorage.setItem("cf-mode", playbackMode);
    } catch {
      /* ignore */
    }
  }, [playbackMode]);

  // Reset pause / quiz state when the cursor changes (new step = fresh play)
  useEffect(() => {
    setIsPaused(false);
    setQuizAnswered(false);
  }, [stepper.cursor.chapter, stepper.cursor.step]);

  const handleAdvance = useCallback(() => {
    if (isPaused) return;
    stepper.next();
  }, [stepper, isPaused]);

  // Hold auto-advance while a quiz is open and unanswered.
  const quizOpen = Boolean(quiz) && !quizAnswered;
  const audioAdvance = useCallback(() => {
    if (quizOpen) return;
    handleAdvance();
  }, [quizOpen, handleAdvance]);

  useAudioPlayer({
    src: `/audio/${ch.id}/${stepper.cursor.step + 1}.mp3`,
    paused: isPaused,
    mode,
    autoStarted,
    onAutoAdvance: audioAdvance,
    estimateFallbackMs: estimateMs(stepText),
  });

  const onAdvance = useCallback(() => {
    if (mode === "auto" && !autoStarted) return;
    if (isPaused) return;
    if (quizOpen) return; // don't advance past an unanswered quiz
    stepper.next();
  }, [mode, autoStarted, stepper, isPaused, quizOpen]);

  // Fullscreen toggle (Fullscreen API on the main area)
  const fsRef = useRef<HTMLDivElement | null>(null);
  const [isFs, setIsFs] = useState(false);
  // fsEmulated = the Fullscreen API was unavailable/rejected, so we fake
  // "fullscreen" with a CSS rotate (used on iOS, where element fullscreen
  // is flaky and the Orientation Lock API does not exist).
  const [fsEmulated, setFsEmulated] = useState(false);
  // fsPortrait = we are (really or emulated) fullscreen AND the viewport is
  // portrait → the stage should rotate to landscape.
  const [fsPortrait, setFsPortrait] = useState(false);

  // ChapterMenu visibility — collapsed by default to give Stage the full
  // 1920×1080 viewport. Reopens on hover near the left edge or on the
  // explicit "≡" button in the top-left corner. Closes when the cursor
  // leaves both the menu and the trigger strip.
  const [menuOpen, setMenuOpen] = useState(false);
  const menuHideTimer = useRef<number | null>(null);
  function showMenu() {
    if (menuHideTimer.current != null) {
      window.clearTimeout(menuHideTimer.current);
      menuHideTimer.current = null;
    }
    setMenuOpen(true);
  }
  function hideMenuDelayed() {
    if (menuHideTimer.current != null) window.clearTimeout(menuHideTimer.current);
    menuHideTimer.current = window.setTimeout(() => setMenuOpen(false), 220);
  }
  const toggleFullscreen = useCallback(() => {
    if (!fsRef.current) return;
    // Already in CSS-emulated fullscreen → just exit it.
    if (fsEmulated) {
      setFsEmulated(false);
      setFsPortrait(false);
      return;
    }
    if (!document.fullscreenElement) {
      const el = fsRef.current;
      const req = el.requestFullscreen?.bind(el);
      if (req) {
        req()
          .then(() => {
            /* fullscreenchange handler below does the rest */
          })
          .catch(() => {
            // Fullscreen API rejected (e.g. iOS < 16.4) — emulate landscape
            // via CSS so the 16:9 stage still fills the screen.
            setFsEmulated(true);
            setFsPortrait(window.innerHeight > window.innerWidth);
          });
      } else {
        // No Fullscreen API at all → emulate landscape via CSS.
        setFsEmulated(true);
        setFsPortrait(window.innerHeight > window.innerWidth);
      }
    } else {
      document.exitFullscreen().catch(() => {});
    }
  }, [fsEmulated]);

  // Keep the forced-landscape state in sync with reality. When fullscreen
  // engages on a portrait phone, rotate the stage to landscape (CSS) and
  // try the native Orientation Lock (Android). Re-evaluate if the device
  // is rotated while fullscreen.
  useEffect(() => {
    function onFsChange() {
      const active = document.fullscreenElement === fsRef.current;
      setIsFs(active);
      const portrait = window.innerHeight > window.innerWidth;
      setFsPortrait(active && portrait);
      if (active && portrait) {
        try {
          screen.orientation?.lock("landscape").catch(() => {});
        } catch {
          /* Orientation Lock API unavailable (iOS) — CSS rotate handles it */
        }
      } else if (!active) {
        try {
          screen.orientation?.unlock();
        } catch {
          /* not supported */
        }
        setFsEmulated(false);
      }
    }
    function onViewport() {
      const active = document.fullscreenElement === fsRef.current;
      setFsPortrait((active || fsEmulated) && window.innerHeight > window.innerWidth);
    }
    document.addEventListener("fullscreenchange", onFsChange);
    window.addEventListener("resize", onViewport);
    window.addEventListener("orientationchange", onViewport);
    return () => {
      document.removeEventListener("fullscreenchange", onFsChange);
      window.removeEventListener("resize", onViewport);
      window.removeEventListener("orientationchange", onViewport);
    };
  }, [fsEmulated]);

  const togglePause = useCallback(() => setIsPaused((p) => !p), []);

  // Keyboard shortcuts:
  //   Space  → toggle play / pause
  //   F      → toggle fullscreen
  //   M      → cycle playback mode (manual → audio → auto)
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement | null;
      if (
        target instanceof HTMLInputElement ||
        target instanceof HTMLTextAreaElement
      ) return;
      if (e.key === " " || e.code === "Space") {
        e.preventDefault();
        e.stopPropagation();
        // Drop focus from any focused button so a subsequent Space
        // doesn't re-trigger that button's click (browser default
        // behavior). Without this, hitting Space while a button is
        // focused can both pause AND advance.
        if (document.activeElement instanceof HTMLElement) {
          document.activeElement.blur();
        }
        // Space semantics — never advance the stepper:
        //   1. AutoStartGate visible (page just opened with ?auto=1,
        //      user hasn't gestured yet) → dismiss the gate and start
        //      auto playback. (Bypass the pause flag entirely.)
        //   2. AutoStartGate dismissed + isPaused → resume.
        //   3. AutoStartGate dismissed + !isPaused → pause.
        if (mode === "auto" && !autoStarted) {
          setAutoStarted(true);
        } else {
          togglePause();
        }
      } else if (e.key === "f" || e.key === "F") {
        e.preventDefault();
        toggleFullscreen();
      }
    };
    // Use capture phase so we run BEFORE any focused-element default
    // behavior (browser would fire button.click() on Space for focused
    // buttons) and we can intercept every key event first. The parent
    // is the single source of truth for Space.
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [togglePause, toggleFullscreen, mode, autoStarted, setAutoStarted]);

  return (
    <div
      className={`app-root ${menuOpen ? "app-root--menu-open" : ""} ${
        fsPortrait ? "app-root--fs-portrait" : ""
      }`}
      ref={fsRef}
    >
      <ChapterMenu
        course={course}
        currentChapterId={ch.id}
        jumpTo={(chapterIndex, step) => stepper.jumpToChapter(chapterIndex, step)}
        onMouseEnter={showMenu}
        onMouseLeave={hideMenuDelayed}
      />

      <div
        className="cm-trigger"
        onMouseEnter={showMenu}
        onMouseLeave={hideMenuDelayed}
        onFocus={showMenu}
      >
        <button
          type="button"
          className="cm-trigger-btn"
          onClick={() => (menuOpen ? setMenuOpen(false) : showMenu())}
          aria-label="显示课程菜单"
          aria-expanded={menuOpen}
          title="菜单"
          data-no-advance
        >
          <span aria-hidden="true">≡</span>
        </button>
      </div>

      <div className="app-main">
        <AutoStartGate
          visible={mode === "auto" && !autoStarted}
          onStart={() => setAutoStarted(true)}
        />

        <div className="app-stage-area">
          <Stage onAdvance={onAdvance} layout="embedded">
            <Cmp step={stepper.cursor.step} />
          </Stage>
        </div>

        <SubtitleStep chapters={chapters} cursor={stepper.cursor} />

        {course.courseId === "single" ? (
          <ProgressBar
            chapters={chapters}
            cursor={stepper.cursor}
            onJumpChapter={(idx, step) => stepper.jumpToChapter(idx, step)}
          />
        ) : (
          <AppDock
            railPct={computeSegmentProgress(chapters, stepper.cursor, course).stepPct}
            readout={
              <CourseProgressReadout
                chapters={chapters}
                cursor={stepper.cursor}
                course={course}
              />
            }
            playbackPhase={isPaused ? "paused" : "playing"}
            isPaused={isPaused}
            onTogglePause={togglePause}
            onFullscreen={toggleFullscreen}
            isFullscreen={isFs}
            hint="Space 暂停/播放 · F 全屏 · 鼠标点屏幕推进"
          />
        )}

        {course.courseId === "single" && (
          <ModeControls
            playbackPhase={isPaused ? "paused" : "playing"}
            onModeChange={onModeChange}
            onFullscreen={toggleFullscreen}
            isFullscreen={isFs}
            isPaused={isPaused}
            onTogglePause={togglePause}
            hint="Space 暂停/播放 · F 全屏 · 鼠标点屏幕推进"
          />
        )}

        {quiz && (
          <div className="app-quiz-overlay">
            <QuizPanel
              question={quiz.question}
              onSubmit={() => setQuizAnswered(true)}
            />
          </div>
        )}
      </div>
    </div>
  );
}
